repository: tomjoht/documentation-theme-jekyll
baseurl: "/winnvm"
output: web
topnav_title: WinNvm
site_title: Windows NodeJS Version Manager
company_name: WinNvm
github_editme_path: seenukarthi/winnvm/blob/master/docs/
disqus_shortname: seenukarthi
google_analytics: UA-38595132-1
exclude:
  - .idea/
  - .gitignore
feedback_subject_line: Windows NodeJS Version Manager
feedback_email: seenukarthi@gmail.com
highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav

# these are defaults used for the frontmatter for these file types

sidebars:
- home_sidebar
- mydoc_sidebar
- product1_sidebar
- product2_sidebar
- other

description: "Intended as a documentation theme based on Jekyll for technical writers documenting software and other technical products, this theme has all the elements you would need to handle multiple products with both multi-level sidebar navigation, tags, and other documentation features."
# the description is used in the feed.xml file

# needed for sitemap.xml file only
url: https://seenukarthi.com/winnvm/
