name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v1
        name: Checkout Code

      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet Packages
        run: nuget restore WinNvm.sln

      - name: Build Winnvm
        run: msbuild WinNvm.sln /p:Configuration=Release
